package ProgramUTS_Pertama;

public class fPembayaran extends javax.swing.JFrame {

    public fPembayaran() {
        initComponents();
        mnLogin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cbPaket1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtPaket1 = new javax.swing.JTextField();
        txtHarga1 = new javax.swing.JTextField();
        txtJml1 = new javax.swing.JTextField();
        txtBayar1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbPaket2 = new javax.swing.JComboBox<>();
        txtPaket2 = new javax.swing.JTextField();
        txtHarga2 = new javax.swing.JTextField();
        txtJml2 = new javax.swing.JTextField();
        txtBayar2 = new javax.swing.JTextField();
        cbPaket3 = new javax.swing.JComboBox<>();
        txtPaket3 = new javax.swing.JTextField();
        txtHarga3 = new javax.swing.JTextField();
        txtJml3 = new javax.swing.JTextField();
        txtBayar3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnExit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Pembayaran");

        jLabel1.setText("No. Meja");

        cbPaket1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Nasi-", "Nasi Putih", "Nasi Goreng", "Nasi Capcay" }));
        cbPaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaket1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ket. Paket");

        jLabel3.setText("Harga");

        jLabel4.setText("Jml Beli");

        jLabel5.setText("Bayar");

        cbPaket2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Ayam-", "Ayam Penyet", "Ayam Bakar", "Ayam Goreng" }));
        cbPaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaket2ActionPerformed(evt);
            }
        });

        cbPaket3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Minuman-", "Aqua", "Jus Alpukat", "Jus Jeruk" }));
        cbPaket3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaket3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Pesanan");

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("DejaVu Serif", 2, 24)); // NOI18N
        jLabel7.setText("Warung Makan Sederhana");
        jLabel7.setToolTipText("");

        mnFile.setText("Menu");
        mnFile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mnLogin.setText("Login");
        mnLogin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnLoginItemStateChanged(evt);
            }
        });
        mnFile.add(mnLogin);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnFile.add(mnLogout);
        mnFile.add(jSeparator1);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnFile.add(mnExit);

        jMenuBar1.add(mnFile);

        mnHelp.setText("Help");

        mnInfo.setText("Info");
        mnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInfoActionPerformed(evt);
            }
        });
        mnHelp.add(mnInfo);

        jMenuBar1.add(mnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(424, 424, 424)
                            .addComponent(jLabel6)
                            .addGap(26, 26, 26)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbPaket2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)
                                .addComponent(txtPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJml2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJml3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBayar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbPaket1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(31, 31, 31)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField1)
                                            .addComponent(txtPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtJml1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(txtBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJml1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJml2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBayar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaket3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJml3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBayar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBayar)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        dispose();
        new dialogLogin(this,false).setVisible(true);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnLoginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnLoginItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mnLoginItemStateChanged

    private void cbPaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaket1ActionPerformed
        int nasiPutih, nasiGoreng, nasiCapcay;
        int paket = cbPaket1.getSelectedIndex();
        switch(paket){
            case 0:
                break;
            case 1:
                txtPaket1.setText("Paket 1");
                txtHarga1.setText(String.valueOf(5000));
                break;
            case 2:
                txtPaket1.setText("Paket 1");
                txtHarga1.setText(String.valueOf(12000));
                break;
            case 3:
                txtPaket1.setText("Paket 1");
                txtHarga1.setText(String.valueOf(15000)); 
                break;
        }
    }//GEN-LAST:event_cbPaket1ActionPerformed

    private void cbPaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaket2ActionPerformed
        int ayamPenyet, ayamBakar, ayamGoreng;
        int paket = cbPaket2.getSelectedIndex();
        switch(paket){
            case 0:
                break;
            case 1:
                txtPaket2.setText("Paket 2");
                txtHarga2.setText(String.valueOf(11000));
                break;
            case 2:
                txtPaket2.setText("Paket 2");
                txtHarga2.setText(String.valueOf(13000));
                break;
            case 3:
                txtPaket2.setText("Paket 2");
                txtHarga2.setText(String.valueOf(10000)); 
                break;
        }
    }//GEN-LAST:event_cbPaket2ActionPerformed

    private void cbPaket3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaket3ActionPerformed
        int aqua, jusAlpukat, jusJeruk;
        int paket = cbPaket3.getSelectedIndex();
        switch(paket){
            case 0:
                break;
            case 1:
                txtPaket3.setText("Paket 3");
                txtHarga3.setText(String.valueOf(4000));
                break;
            case 2:
                txtPaket3.setText("Paket 3");
                txtHarga3.setText(String.valueOf(8000));
                break;
            case 3:
                txtPaket3.setText("Paket 3");
                txtHarga3.setText(String.valueOf(7000)); 
                break;
        }
    }//GEN-LAST:event_cbPaket3ActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // Mengambil Input Jumlah Pembelian
        int jumlahPaket1 = Integer.parseInt(txtJml1.getText());
        int jumlahPaket2 = Integer.parseInt(txtJml2.getText());
        int jumlahPaket3 = Integer.parseInt(txtJml3.getText());
        
        // Mengambil Input Harga Paket
        int hargaPaket1 = Integer.parseInt(txtHarga1.getText());
        int hargaPaket2 = Integer.parseInt(txtHarga2.getText());
        int hargaPaket3 = Integer.parseInt(txtHarga3.getText());
        
        // Membuat Variabel Bayar Tiap Paket
        int bayarPaket1 = jumlahPaket1*hargaPaket1;
        int bayarPaket2 = jumlahPaket2*hargaPaket2;
        int bayarPaket3 = jumlahPaket3*hargaPaket3;
        
        // Set Text Bayar
        txtBayar1.setText(String.valueOf("Rp."+bayarPaket1));
        txtBayar2.setText(String.valueOf("Rp."+bayarPaket2));
        txtBayar3.setText(String.valueOf("Rp."+bayarPaket3));
        
        // Membuat Variabel Total Pesanan dan Set ke Text Total
        int total = bayarPaket1+bayarPaket2+bayarPaket3;
        txtTotal.setText(String.valueOf("Rp."+total));
        
    }//GEN-LAST:event_btnBayarActionPerformed

    private void mnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInfoActionPerformed
        new dialogHelp(this,false).setVisible(true);
    }//GEN-LAST:event_mnInfoActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JComboBox<String> cbPaket1;
    private javax.swing.JComboBox<String> cbPaket2;
    private javax.swing.JComboBox<String> cbPaket3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnInfo;
    private javax.swing.JMenuItem mnLogin;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JTextField txtBayar1;
    private javax.swing.JTextField txtBayar2;
    private javax.swing.JTextField txtBayar3;
    private javax.swing.JTextField txtHarga1;
    private javax.swing.JTextField txtHarga2;
    private javax.swing.JTextField txtHarga3;
    private javax.swing.JTextField txtJml1;
    private javax.swing.JTextField txtJml2;
    private javax.swing.JTextField txtJml3;
    private javax.swing.JTextField txtPaket1;
    private javax.swing.JTextField txtPaket2;
    private javax.swing.JTextField txtPaket3;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
